### ISSUE TITLE
HMPDACC downloads not working

### ISSUE THREAD

**Issue by whottel** [iqbal-lab-org/clockwork#100]
Similar to Issue #49, the urls in `download_tb_reference_files.pl`  for HMPDACC data do not seem to be working in the that connection will always time out.
I was able to download these files by separately running:
```
wget http://downloads.hmpdacc.org/data/HMBSA/Saliva.tar.bz2
wget http://downloads.hmpdacc.org/data/HMBSA/Throat.tar.bz2
wget http://downloads.hmpdacc.org/data/HMBSA/Tongue_dorsum.tar.bz2
wget http://downloads.hmpdacc.org/data/HMBSA/Buccal_mucosa.tar.bz2
wget http://downloads.hmpdacc.org/data/HMBSA/Palatine_Tonsils.tar.bz2
```

**Comment by martinghunt** [comment]
Argh, these URLs are a moving target!
Thanks for providing working ones. I've updated the script on tip of master (for the record, commit 9ccbaf32e0f0792b7b3cd01b885ddd7b1a2295f4).

Not sure how you're running it, but if it's singularity then there's no need to rebuild the container, you can just do this:

```
git clone https://github.com/iqbal-lab-org/clockwork.git
singularity exec clockwork_container.img ./clockwork/scripts/download_tb_reference_files.pl outdir
```

**Comment by whottel** [comment]
Great, thanks!
