### ISSUE TITLE
 Missed INH-R caused by deletion of the entire katG gene

### ISSUE THREAD

**Issue by xrazmo** [iqbal-lab-org/clockwork#105]
Hi, 
I am using the script version of clockwork (singularity image v0.11.3), [sp3predict ](https://github.com/philipwfowler/sp3predict) and [NC_000962.3_CRyPTIC_v1.311_GARC1_RUS](https://github.com/oxfordmmm/tuberculosis_amr_catalogues/blob/public/catalogues/NC_000962.3/NC_000962.3_CRyPTIC_v1.311_GARC1_RUS.csv) catalogue to characterize a well-known isoniazid-resistant isolate (ATCC35822) which has lost the entire katG gene. However, the output of DST prediction and also the produced VCF files (cortex, samtools and final) did not report the deletion. It would be great if you could give me some tips on what has gone wrong.

Thanks.

**Comment by martinghunt** [comment]
Could you please let me know which reads you used? Would also be useful if you could attach the three VCF files.

**Comment by iqbal-lab** [comment]
Thank you! Is there any way you could share the reads?

**Comment by xrazmo** [comment]
The reads are available [here](https://drive.google.com/drive/folders/1x30c2-ycd6dedKq-sdsAWol5HQiy0m2y?usp=sharing).

**Comment by martinghunt** [comment]
The deletion is 50kb, which is far too big for Cortex (and samtools!). Sorry, but clockwork won't call this. We have a tool in development which would integrate gene absence info into dst prediction, but is not ready yet.

<img width="1158" alt="image" src="https://user-images.githubusercontent.com/4937411/207620334-0dc0c3cd-dd9c-44de-8aa5-3b8663a71a28.png">

**Comment by xrazmo** [comment]
I see, thanks again :)
