### ISSUE TITLE
the minimum read depth for variant calling 

### ISSUE THREAD

**Issue by alantsangmb** [iqbal-lab-org/clockwork#107]
What is the minimum read depth for variant calling by default?
How could we adjust this parameter?

Thank you so much.

**Comment by iqbal-lab** [comment]
Hi there! The final VCF includes coverage information on both alleles, so you could simply set a filter on that? (Clockwork does not delete any VCF rows, it simply marks them in the FILTER column). @martinghunt , what is the default min depth?

**Comment by martinghunt** [comment]
Default depth filter is 2. Like @iqbal-lab says, the VCF has everything anyway so is easiest to re-filter the VCF file.

The filters are described here:
https://github.com/iqbal-lab-org/minos/wiki/Minos-in-single-sample-mode#call-filters

The filter options are not exposed by the clockwork variant call pipeline. If you really wanted, you could rerun the final minos command but add in your own command line options to minos (clockwork uses the default minos options).

**Comment by alantsangmb** [comment]
Thank you so much
