### ISSUE TITLE
singularity installation instructions

### ISSUE THREAD

**Issue by flashton2003** [iqbal-lab-org/clockwork#40]
I'm installing Clockwork via singularity as recommended. I think there has been some changes to singularity since the instructions were written. When I ran:

`sudo singularity create -s 8000 clockwork_container.img`

It returned this warning:

```
WARNING: The create command is deprecated, and will be removed
WARNING: To create, use the image.create command.
WARNING: Use the build command to create and build an image in a single step.
Creating empty 8000MiB image file: clockwork_container.img
Formatting image with ext3 file system
Image is done: clockwork_container.img
```

Then, on the next step:

`sudo singularity bootstrap clockwork_container.img clockwork_container.def`

It failed with this error:

```
WARNING: The bootstrap command is deprecated and will be removed in a future release.
WARNING: Use the build command like so:
WARNING: singularity build clockwork_container.img clockwork_container.def
ERROR: clockwork_container.img is not an image file
Cleaning up...
```

There was no difference if I used this instead:

`sudo singularity image.create -s 8000 clockwork_container.img` 

It works if i use this:

`sudo  singularity build clockwork_container.img clockwork_container.def`

**Comment by minisciencegirl** [comment]
For the version of singularity (2.5.2-dist) that I am using, it's better to run 
`sudo singularity image.create -s 8000 clockwork_container.img` as @flashton2003 noted that it's deprecated.

And to run the `bootstrap` command, I needed to have debootstrap installed first.

**Comment by martinghunt** [comment]
Thanks @flashton2003 and @minisciencegirl. I've updated the instructions on the wiki.
