### ISSUE TITLE
Run pipelines with multiple threads

### ISSUE THREAD

**Issue by flashton2003** [iqbal-lab-org/clockwork#42]
I guess that you have parallelisation setup within the database way of organising jobs, but it might be nice to expose a threads option for e.g. qc.nf, variant_call.nf, etc.

**Comment by martinghunt** [comment]
Sorry, can you clarify? Do you mean number of threads if not using a database?

**Comment by flashton2003** [comment]
Sorry. I mean, is there an easy way to run the variant calling pipeline and give multiple threads to samtools and/or cortex etc?

**Comment by iqbal-lab** [comment]
no there isn't, sorry.
