### ISSUE TITLE
Is minos/final.vcf the output to take forward?

### ISSUE THREAD

**Issue by flashton2003** [iqbal-lab-org/clockwork#43]
Just a minor documentation thing really, I'm guess that minos/final.vcf is the file to take forward for further analyses, but it would be good for this to be mentioned in the documentation somewhere.

**Comment by martinghunt** [comment]
Yes, that's the one. In case you want them, there's also the samtools and cortex VCFs kept. Will update the docs.

**Comment by flashton2003** [comment]
Great, thank you!
