### ISSUE TITLE
Downloads from HMPDACC not working

### ISSUE THREAD

**Issue by mbhall88** [iqbal-lab-org/clockwork#49]
The FTP URLs here https://github.com/iqbal-lab-org/clockwork/blob/be1f6ea49debf8cb2b8f1ba974df2dc567d150fd/scripts/make_pipeline_reference_files.pl#L40-L44 are not working. When trying to run `wget` or `curl` on them it says `The server refuses login`.  

I have sent a feedback request form to them to mention this.  

Some alternatives could be they have this data transfer tool https://github.com/IGS/portal_client

**Comment by mbhall88** [comment]
I have tested some of these URLs and this issue seems to be resolved now.

**Comment by pr0xxy** [comment]
If those URLs ever worked they not working now... It is causing my build to fail.

**Comment by iqbal-lab** [comment]
Any Idea @mbhall88?

**Comment by martinghunt** [comment]
Sorry, not sure what to say because I can't reproduce it. @pr0xxy can you confirm if this fails for you?

```
$ wget ftp://public-ftp.hmpdacc.org/HMBSA/Tongue_dorsum.tar.bz2
--2019-08-13 18:26:43--  ftp://public-ftp.hmpdacc.org/HMBSA/Tongue_dorsum.tar.bz2
           => ‘Tongue_dorsum.tar.bz2’
Resolving public-ftp.hmpdacc.org (public-ftp.hmpdacc.org)... 134.192.125.24
Connecting to public-ftp.hmpdacc.org (public-ftp.hmpdacc.org)|134.192.125.24|:21... connected.
Logging in as anonymous ... Logged in!
==> SYST ... done.    ==> PWD ... done.
==> TYPE I ... done.  ==> CWD (1) /HMBSA ... done.
==> SIZE Tongue_dorsum.tar.bz2 ... 99564303
==> PASV ... done.    ==> RETR Tongue_dorsum.tar.bz2 ... done.
Length: 99564303 (95M) (unauthoritative)

Tongue_dorsum.tar.bz2                     100%[=====================================================================================>]  94.95M  1008KB/s    in 80s

2019-08-13 18:28:04 (1.19 MB/s) - ‘Tongue_dorsum.tar.bz2’ saved [99564303]
```

**Comment by mbhall88** [comment]
> Any Idea @mbhall88?

As per https://github.com/iqbal-lab-org/clockwork/issues/49#issuecomment-520953462 I am able to download the provided example.

@pr0xxy are you able to provide an example of the error log so we can see whether it is a specific one of the URLs that is failing.

**Comment by martinghunt** [comment]
The URLs are all updated in release 0.7.8, so should work now
https://github.com/iqbal-lab-org/clockwork/releases/tag/v0.7.8
Note that the download of these genomes is now separated from the singularity build.
