### ISSUE TITLE
Error building singularity container

### ISSUE THREAD

**Issue by mezewudo** [iqbal-lab-org/clockwork#52]
I had this error after a while processing the singularity build command:

Error running: enaDataGet -d tmp.7933 -f fasta CVQQ00000000 at /clockwork/scripts/make_pipeline_reference_files.pl line 189.
ABORT: Aborting with RETVAL=255

I do not know what the issue is, it just says something unexpected went wrong, and to try again and if problem persists, ask for assistance.

Thanks for your time.

**Comment by pr0xxy** [comment]
Same here:

+ /clockwork/scripts/make_pipeline_reference_files.pl /clockwork/reference_genomes/
------------------- download genomes --------------------
enaDataGet -d tmp.3901 -f fasta CCBF00000000
ERROR: Something unexpected went wrong please try again.
If problem persists, please contact datasubs@ebi.ac.uk for assistance.
Error running: enaDataGet -d tmp.3901 -f fasta CCBF00000000 at /clockwork/scripts/make_pipeline_reference_files.pl line 190.
ABORT: Aborting with RETVAL=255
Cleaning up...

**Comment by iqbal-lab** [comment]
Sorry for not addressing this sooner. I'll look tomorrow. Cc @martinghunt

**Comment by martinghunt** [comment]
Strange. I just ran it and it worked for me:

```
$ ./make_pipeline_reference_files.pl OUT
------------------- download genomes --------------------
wget -nv -O CBMO000000000.fa 'https://eutils.ncbi.nlm.nih.gov/entrez/eutils/efetch.fcgi?db=nucleotide&rettype=fasta&retmode=text&id=CBMO000000000'
2019-08-13 18:21:05 URL:https://eutils.ncbi.nlm.nih.gov/entrez/eutils/efetch.fcgi?db=nucleotide&rettype=fasta&retmode=text&id=CBMO000000000 [1] -> "CBMO000000000.fa" [1]
enaDataGet -d tmp.2481 -f fasta CCBF00000000
Completed
mv tmp.2481/* CCBF00000000.fa.gz
rm -r tmp.2481
enaDataGet -d tmp.2481 -f fasta CWKH00000000
...
```

**Comment by martinghunt** [comment]
@pr0xxy did it hang for ages on the line:
`enaDataGet -d tmp.3901 -f fasta CCBF00000000`
before throwing the error? Or was it instant? I have had it hang on me and had to kill it. (See issue #53).

**Comment by mezewudo** [comment]
For me it did not hang for long before throwing up the error. But I have
run this on multiple occasions and it always fails at the enaDataGet
 command for some reason.

**Comment by pr0xxy** [comment]
> @pr0xxy did it hang for ages on the line:
> `enaDataGet -d tmp.3901 -f fasta CCBF00000000`
> before throwing the error? Or was it instant? I have had it hang on me and had to kill it. (See issue #53).
Trying to build a singularity image:

git clone https://github.com/iqbal-lab-org/clockwork.git

singularity image.create -s 8000 clockwork_container.img
singularity build clockwork_container.img clockwork_container.def Singularity

The script is called from clockwork_container.def

**Comment by martinghunt** [comment]
Are you behind a firewall? Could it be blocking the download?

**Comment by pr0xxy** [comment]
> Are you behind a firewall? Could it be blocking the download?

So I found out the FTP protocol has newly been blocked by the firewall. It seems I will need an HTTP mirror.  I will update this with what happens.

Thanks,

pr0xxy

**Comment by martinghunt** [comment]
The URLs are updated for those downloads, and are now HTTP instead of FTP. Please see release 0.7.8 https://github.com/iqbal-lab-org/clockwork/releases/tag/v0.7.8
