### ISSUE TITLE
Commands run and command output

### ISSUE THREAD

**Issue by dvolk** [iqbal-lab-org/clockwork#57]
It would be nice if the clockwork command would output:

- the full commands run
- the output of those commands

I assume It's all sequential so the output could be something like

    *** running command: bwa mem .....
    stdout:
    <command stdout here>
    stderr:
    <command stderr here>
    *** running command: ...

Written either to stdout or to a file

**Comment by martinghunt** [comment]
This is now added to tip of master. Will be a new release next week (a few other things I want to change first).

**Comment by dvolk** [comment]
Great, thanks!

**Comment by martinghunt** [comment]
There's a new release 0.8.0, with the logging.
