### ISSUE TITLE
gVCF output

### ISSUE THREAD

**Issue by iqbal-lab** [iqbal-lab-org/clockwork#65]
Specifically for PHE, they want to collect per-sample VCFs and use them for distance calculations without ever having to regenotype. Their hack/route is to dump a gVCF and fasta for each sample. At every position of the reference, you either: give the called allele from a normal VCF, give the ref allele if uncalled and the pileup supports it,and give N if unsure.

Comments
1. Given the high discovery power of clockwork, just assuming REF everywhere not called is not terrible, especially given we assume the use of a mask. So the cheap and dirty solution is simply to do that. Not super-keen.
2. We could scan the pileup quickly and collect a list of confident REF sites, and then combine this with the normal VCF - just automatically calling N at all the places not confident REF and not in the normal VCF

**Comment by martinghunt** [comment]
I agree with 2 (but parse normal VCF first, then look in the pileup for remaining positions)

**Comment by iqbal-lab** [comment]
great

**Comment by martinghunt** [comment]
Need to decide on definition of "confident". Can we use COMPASS rules?

**Comment by martinghunt** [comment]
Also need to decide what to do with indels.

**Comment by iqbal-lab** [comment]
i think this can be closed, fixed in release v0.9.0. closing, feel free to reopen if i've missed something
