### ISSUE TITLE
Multi-thread remove contamination option?

### ISSUE THREAD

**Issue by flashton2003** [iqbal-lab-org/clockwork#67]
Hello,

I'm running the remove_contam.nf script, is there a way to run this workflow with multiple threads? Since we are mapping to large ref genome(s), it takes some time.

Thanks,

Phil

**Comment by martinghunt** [comment]
Hi Phil,

Is this running the pipeline on a single sample (not using a database)? If so, I could easily expose BWA's threads option as a parameter to the nextflow script. That's where it spends most of its time.

Martin

**Comment by flashton2003** [comment]
Hi Martin,

Yes, running on a single sample. Would be great ot have a threads option which was communicated to BWA.

Thanks!

Phil

**Comment by martinghunt** [comment]
Done! Is there on tip of master.

**Comment by martinghunt** [comment]
Use the option `--mapping_threads 42` (or your favourite number) with the nextflow script.

**Comment by flashton2003** [comment]
Awesome, thank you!

**Comment by martinghunt** [comment]
@flashton2003 sorry, I missed telling nextflow how many threads the mapping process would use, although the call to BWA itself was using the threads option. I just fixed that, so you'll need to git pull to get that fix (https://github.com/iqbal-lab-org/clockwork/commit/eb333d7bc92bf0522afc256ac34afa5882683ebe).

**Comment by flashton2003** [comment]
Thanks Martin!
