### ISSUE TITLE
Remove_contamination command throws up AssertionError

### ISSUE THREAD

**Issue by mezewudo** [iqbal-lab-org/clockwork#77]
I tried running this command to remove contaminating reads from my references prepared folling the instructions on your wiki:

clockwork remove_contam ref_data/OUT/remove_contam_metadata.tsv ERR552106_sort.bam ERR552106_count.txt ERR552106_1.fastq ERR552106_2.fastq

I ended up with this error message below:

Traceback (most recent call last):
  File "/usr/local/bin/clockwork", line 4, in <module>
    __import__('pkg_resources').run_script('clockwork==0.9.0', 'clockwork')
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 658, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 1445, in run_script
    exec(script_code, namespace, namespace)
  File "/usr/local/lib/python3.6/dist-packages/clockwork-0.9.0-py3.6.egg/EGG-INFO/scripts/clockwork", line 960, in <module>
  File "/usr/local/lib/python3.6/dist-packages/clockwork-0.9.0-py3.6.egg/clockwork/tasks/remove_contam.py", line 17, in run
  File "/usr/local/lib/python3.6/dist-packages/clockwork-0.9.0-py3.6.egg/clockwork/contam_remover.py", line 177, in run
AssertionError

I am not sure if I am doing something wrong, but the AssertionError suggests maybe something to check in the actual code?

**Comment by martinghunt** [comment]
The remove_contam pipeline is intended to be run using the nextflow script `remove_contam.nf`. Sorry but many of the `clockwork xyz` commands are not documented simply because they weren't intended to be run directly, but by nextflow.

That said, my guess is that `ERR552106_sort.bam` is sorted by coordinate. It needs to be sorted by name (ie what most read mappers would output directly without sorting).

**Comment by mezewudo** [comment]
I thought as much that the issue is from the .bam file. Unfortunately, I do not have admin privileges in the Linux machine I am using, and the next alternative I have to running clockwork using nextflow is using the stepwise commands. 

The bam file was actually created from the 'clockwork map_reads' step. I have tried to sort the file by reads name using either of samtools or picard tools, and noticed marginal improvements (some portion of the fastqs were written before the error was thrown again). Any thoughts on a tool I could use to sort the .bam file (which has alignments to different reference genomes contaminated and not contaminated) by reads name or a suggestion on what I could do here.

Thanks!

**Comment by martinghunt** [comment]
You don't need admin to install or run nextflow.

**Comment by mezewudo** [comment]
I worded my comment wrongly, I can install and run nextflow, but the clockwork tool itself was installed by admin and that is where I am having issues.

**Comment by martinghunt** [comment]
Sorry, I don't understand the issue. Can you run the nextflow pipeline instead of the individual clockwork scripts?

**Comment by mezewudo** [comment]
I cannot run the nextflow pipeline. Maybe it has to do with the way it was installed in the system I am using, the only way I get clockwork to work is to call the clockwork command which gives me the individual command options:

--------------------------------------------------------------------------------------------------------------
usage: clockwork <tasks> <options>

script to run clockwork helper tasks

optional arguments:
  -h, --help            show this help message and exit

Available tasks:

    cortex              Runs cortex
    mykrobe_predict     Runs mykrobe predict
    mykrobe_predict_make_jobs_tsv
                        Finds which sample need running mykrobe_predict
                        pipeline
    reference_prepare   Makes reference genome files for use with pipelines
    db_add_mykrobe_panel
                        Add mykrobe panel to database
    db_finished_pipeline_update
                        Update database after pipeline has been run
    db_finished_pipeline_update_failed_jobs
                        Update database with failed jobs at end of pipeline
    ena_download        Download reads from the ENA
    ena_submit_reads    Submit reads to the ENA
    find_data           Report IDs from database and files on disk
    make_empty_db       Make new database with empy tables
    minos_make_multi_sample_input
                        Make input TSV file for minos multi_sample_pipeline
    fastqc              Wrapper for FASTQC
    generic_pipeline_make_jobs_tsv
                        Finds which sample need running a generic pipeline
    gvcf_from_minos_and_samtools
                        Makes gVCF from minos and samtools VCF files
    gvcf_to_fasta       Makes FASTA file from gVCF file made by
                        gvcf_from_minos_and_samtools
    import_read_pair    Imports a read pair
    make_import_spreadsheet
                        Makes an import spreadsheet xlsx file, with just the
                        column headings
    validate_spreadsheet
                        Validates import spreadsheet
    import_spreadsheet  Parses import spreadsheet and makes output for
                        import_read_pair
    map_reads           Maps reads, removes duplicates, outputs sorted BAM
                        file
    qc_make_jobs_tsv    Finds which samples need running qc pipeline
    fake_remove_contam  Fake remove contaminated reads
    remove_contam       Remove contaminated reads from SAM or BAM
    fake_remove_contam_make_jobs_tsv
                        Finds which sample need running fake_remove_contam
                        pipeline
    remove_contam_make_jobs_tsv
                        Finds which sample need running remove_contam pipeline
    samtools_qc         QCs reads using samtools
    samtools_cortex_vcf_merge
                        Merge samtools and cortex VCF files
    trim_reads          Trim reads using Trimmomatic
    variant_call_make_jobs_tsv
                        Finds which sample need running variant_call pipeline
    version             Get version and exit
--------------------------------------------------------------------------------------------------------------------------

I do not know (nor have access to) the path to where the installation is on the system to I imagine call the nextflow command that should look like this:
nextflow run nextflow/remove_contam.nf --ref_fasta ref_data/OUT/ref.fa   
--ref_metadata_tsv ref_data/OUT/remove_contam_metadata.tsv 
--reads_in1 ERR552106_1.fastq.gz 
--reads_in2 ERR552106_2.fastq.gz 
--outprefix ERR552106_test


Essentially, can I install and run clockwork using nextflow in Unix without admin privileges?

**Comment by martinghunt** [comment]
Sounds like your admin has already installed clockwork. You can get the nextflow scripts from here:
https://github.com/iqbal-lab-org/clockwork/tree/master/nextflow
(or git clone the clockwork repository). Then what happens if you run the nextflow script?

**Comment by mezewudo** [comment]
So here is what happens when I run the nextflow command: nextflow run nextflow/remove_contam.nf --ref_fasta ref_data/OUT/ref.fa --ref_metadata_tsv ref_data/OUT/remove_contam_metadata.tsv --reads_in1 ~/internal/ --reads_in2 ~/internal/input_fastqs/ERR552106_2.fastq.gz --outprefix ERR552106_test

-------------------------------------------------------------------------------------------------------------------------
OpenJDK 64-Bit Server VM warning: Unable to open cgroup memory limit file /sys/fs/cgroup/memory/memory.limit_in_bytes (No such file or directory)
N E X T F L O W  ~  version 19.11.0-edge
Launching `nextflow/remove_contam.nf` [admiring_legentil] - revision: b2f84f8ad4
executor >  local (2)
executor >  local (2)
[9e/18cafd] process > make_jobs_tsv      [100%] 1 of 1 â
[80/54fb2f] process > map_reads (1)      [100%] 1 of 1, failed: 1 â
[-        ] process > sam_to_fastq_files -
Error executing process > 'map_reads (1)'

Caused by:
  Process `map_reads (1)` terminated with an error exit status (127)

Command executed:

  clockwork map_reads --threads 1 --unsorted_sam sample_name /data/ref_data/OUT/ref.fa contam_sam /scicomp/home/krt7/internal /scicomp/home/krt7/internal/input_fastqs/ERR552106_2.fastq.gz

Command exit status:
  127

Command output:
  (empty)

Command error:
  .command.sh: line 2: clockwork: command not found

Work dir:
  /data/work/80/54fb2fccbf4ea44e6c1783b1672b0f

Tip: view the complete command output by changing to the process work dir and entering the command `cat .command.out`
---------------------------------------------------------------------------------------------------------------------------------------------

It seems that inside the Work directory, the script cannot call the 'clockwork' command

**Comment by martinghunt** [comment]
I'm not sure why that's happening. What do `which clockwork` and `echo $PATH` report?

**Comment by mezewudo** [comment]
'which clockwork'

/apps/x86_64/singularity-imgs/clockwork/singularity/clockwork

'echo $PATH'

/apps/x86_64/java/jdk1.8.0_131/jre1.8.0_131/bin:/apps/x86_64/singularity-imgs/clockwork/singularity:/usr/lib64/qt-3.3/bin:/opt/sge/bin/lx-amd64:/usr/local/bin:/usr/bin:/usr/local/sbin:/usr/sbin:/bin:/usr/java/jdk-11.0.4/bin

**Comment by martinghunt** [comment]
Thanks. What does `file /apps/x86_64/singularity-imgs/clockwork/singularity/clockwork` say?

**Comment by mezewudo** [comment]
ok. 

'file   /apps/x86_64/singularity-imgs/clockwork/singularity/clockwork'

/apps/x86_64/singularity-imgs/clockwork/singularity/clockwork: Bourne-Again shell script, ASCII text executable

**Comment by martinghunt** [comment]
I'm trying to figure out how your sysadmin installed clockwork, which is a python script. Can you paste the contents of `/apps/x86_64/singularity-imgs/clockwork/singularity/clockwork` please?

**Comment by mezewudo** [comment]
Yeah, it has just these two lines:

#!/bin/bash

singularity run /apps/x86_64/singularity-imgs/clockwork/singularity/clockwork.img clockwork "$@"

**Comment by martinghunt** [comment]
Thanks. Try running the nextflow command, but add in this option:
`-with-singularity /apps/x86_64/singularity-imgs/clockwork/singularity/clockwork.img`

**Comment by mezewudo** [comment]
It exited with this error message:

-----------------------------------------------------------------------------------------------------------------------------------------
N E X T F L O W  ~  version 19.11.0-edge
Launching `nextflow/remove_contam.nf` [adoring_pare] - revision: b2f84f8ad4
executor >  local (1)
[e9/9b364b] process > make_jobs_tsv      [  0%] 0 of 1
[-        ] process > map_reads          -
executor >  local (1)
[e9/9b364b] process > make_jobs_tsv      [100%] 1 of 1, failed: 1 â
[-        ] process > map_reads          -
[-        ] process > sam_to_fastq_files -
Error executing process > 'make_jobs_tsv'

Caused by:
  Process `make_jobs_tsv` terminated with an error exit status (127)

Command executed:

  echo "reads_in1 reads_in2 counts_tsv reads_contam1 reads_contam2 reads_remove_contam1 reads_remove_contam2 sample_id seqrep_id isolate_id sequence_replicate_number reference_id ref_fasta contam_tsv" > tmp.tsv
  echo "/scicomp/home/krt7/internal/input_fastqs/ERR552106_1.fastq.gz /scicomp/home/krt7/internal/input_fastqs/ERR552106_2.fastq.gz /data/ERR552106_test.counts.tsv /data/ERR552106_test.contam.1.fq.gz /data/ERR552106_test.contam.2.fq.gz /data/ERR552106_test.remove_contam.1.fq.gz /data/ERR552106_test.remove_contam.2.fq.gz . . . . . /data/ref_data/OUT/ref.fa /data/ref_data/OUT/remove_contam_metadata.tsv" >> tmp.tsv
  sed 's/ /t sta/g' tmp.tsv > jobs_tsv
  rm tmp.tsv

Command exit status:
  127

Command output:
  (empty)

Command error:
  env: âsingularityâ: No such file or directory

Work dir:
  /data/work/e9/9b364bedd7529ae133d7cb34bba8a4

Tip: you can replicate the issue by changing to the process work dir and entering the command `bash .command.run`

---------------------------------------------------------------------------------------------------------------------------------------------

**Comment by martinghunt** [comment]
Sorry, this is hard to debug. Thanks for you patience! Can you run these please?

`which singularity`
`which nextflow`
`singularity run /apps/x86_64/singularity-imgs/clockwork/singularity/clockwork.img clockwork --help`

I don't understand how the clockwork script (`/apps/x86_64/singularity-imgs/clockwork/singularity/clockwork`) you're running can run singularity, but nextflow can't.

**Comment by mezewudo** [comment]
Absolutely, thanks for your help debugging, it is not a bother at all.

'which singularity'
/usr/bin/singularity

'which nextflow'
/apps/x86_64/singularity-imgs/nextflow/19.11.0/nextflow

'singularity run /apps/x86_64/singularity-imgs/clockwork/singularity/clockwork.img clockwork --help'

script to run clockwork helper tasks
optional arguments:
-h, --help show this help message and exit
Available tasks:
cortex              Runs cortex
mykrobe_predict     Runs mykrobe predict
mykrobe_predict_make_jobs_tsv
                    Finds which sample need running mykrobe_predict
                    pipeline
reference_prepare   Makes reference genome files for use with pipelines
db_add_mykrobe_panel
                    Add mykrobe panel to database
db_finished_pipeline_update
                    Update database after pipeline has been run
db_finished_pipeline_update_failed_jobs
                    Update database with failed jobs at end of pipeline
ena_download        Download reads from the ENA
ena_submit_reads    Submit reads to the ENA
find_data           Report IDs from database and files on disk
make_empty_db       Make new database with empy tables
minos_make_multi_sample_input
                    Make input TSV file for minos multi_sample_pipeline
fastqc              Wrapper for FASTQC
generic_pipeline_make_jobs_tsv
                    Finds which sample need running a generic pipeline
gvcf_from_minos_and_samtools
                    Makes gVCF from minos and samtools VCF files
gvcf_to_fasta       Makes FASTA file from gVCF file made by
                    gvcf_from_minos_and_samtools
import_read_pair    Imports a read pair
make_import_spreadsheet
                    Makes an import spreadsheet xlsx file, with just the
                    column headings
validate_spreadsheet
                    Validates import spreadsheet
import_spreadsheet  Parses import spreadsheet and makes output for
                    import_read_pair
map_reads           Maps reads, removes duplicates, outputs sorted BAM
                    file
qc_make_jobs_tsv    Finds which samples need running qc pipeline
fake_remove_contam  Fake remove contaminated reads
remove_contam       Remove contaminated reads from SAM or BAM
fake_remove_contam_make_jobs_tsv
                    Finds which sample need running fake_remove_contam
                    pipeline
remove_contam_make_jobs_tsv
                    Finds which sample need running remove_contam pipeline
samtools_qc         QCs reads using samtools
samtools_cortex_vcf_merge
                    Merge samtools and cortex VCF files
trim_reads          Trim reads using Trimmomatic
variant_call_make_jobs_tsv
                    Finds which sample need running variant_call pipeline
version             Get version and exit

**Comment by martinghunt** [comment]
The only idea I've got right now is that it's the nextflow install. Let's try getting your own copy of it. Does this work?

```
curl -s https://get.nextflow.io | bash
./nextflow run hello
```

If that works, the first command should make `nextflow` in your current directory, and then you should get something like this from the second command:
```N E X T F L O W  ~  version 20.07.1
Pulling nextflow-io/hello ...
downloaded from https://github.com/nextflow-io/hello.git
Launching `nextflow-io/hello` [wise_marconi] - revision: 96eb04d6a4 [master]
executor >  local (4)
[4f/994e01] process > sayHello (4) [100%] 4 of 4 ✔
Bonjour world!

Ciao world!

Hola world!

Hello world!
```

And then try running the clockwork pipeline again, but instead of `nextflow`, use `./nextflow` to use the version of nextflow that you just downloaded, instead of `/apps/x86_64/singularity-imgs/nextflow/19.11.0/nextflow`.

**Comment by mezewudo** [comment]
Worked like a charm. Thanks a bunch

**Comment by martinghunt** [comment]
Great! Glad it's working :)
