### ISSUE TITLE
Installation error

### ISSUE THREAD

**Issue by dhcvn** [iqbal-lab-org/clockwork#83]
I got error: _"ERROR  : Failed to set process capabilities"_ at command _"rsync -a ../python ../nextflow ../scripts /tmp/sbuild-670860823/fs/clockwork/"_ while I was building clockwork_container.img. 
I stuck at this step for few days now, anyone can help me?

**Comment by martinghunt** [comment]
Do you have the full output from stdout/stderr please? I'm wondering what it was doing when it made that error.

I just ran a build on the current tip of master (commit 92a53f703a9e262f2c72613536309bf99130c152) and it ran with no errors, took around 1 hour.

**Comment by dhcvn** [comment]
my output show as following: 
```
WARNING: Authentication token file not found : Only pulls of public images will succeed
INFO:    Starting build...
I: Retrieving InRelease
.... (some things like unpacking and configuring)
I: Base system installed successfully.
INFO:    Running setup scriptlet
+ mkdir /tmp/sbuild-739348756/fs/clockwork
+ rsync -a ../python ../nextflow ../scripts /tmp/sbuild-739348756/fs/clockwork/
ERROR  : Failed to set process capabilities
FATAL:   While performing build: while running engine: exit status 1
```
It take about 4-5 minutes to get there. I dont know why.

**Comment by martinghunt** [comment]
The latest release has a singularity container image file included `clockwork_v0.11.1.img`: https://github.com/iqbal-lab-org/clockwork/releases/tag/v0.11.1. Docker containers are here: https://github.com/iqbal-lab-org/clockwork/pkgs/container/clockwork.

MySQL errors during build are probably because MySQL running on the host can cause conflicts - there are comments about that here that might help if you still want to build: https://github.com/iqbal-lab-org/clockwork/wiki#installation

**Comment by PPrasai** [comment]
@martinghunt 
Sorry for bothering you again.
Following the walkthrough for the MySQL version, running the command `singularity exec clockwork.img clockwork make_empty_db db.ini` results in following error:

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/clockwork-0.11.1-py3.8.egg/clockwork/db_maker.py", line 7, in __init__
  File "/usr/local/lib/python3.8/dist-packages/clockwork-0.11.1-py3.8.egg/clockwork/db_connection.py", line 7, in __init__
  File "/usr/local/lib/python3.8/dist-packages/clockwork-0.11.1-py3.8.egg/clockwork/db_connection.py", line 50, in _parse_config_file
  File "/usr/lib/python3.8/configparser.py", line 960, in __getitem__
    raise KeyError(key)
KeyError: 'db_login'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/clockwork", line 4, in <module>
    __import__('pkg_resources').run_script('clockwork==0.11.1', 'clockwork')
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 667, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 1470, in run_script
    exec(script_code, namespace, namespace)
  File "/usr/local/lib/python3.8/dist-packages/clockwork-0.11.1-py3.8.egg/EGG-INFO/scripts/clockwork", line 1019, in <module>
  File "/usr/local/lib/python3.8/dist-packages/clockwork-0.11.1-py3.8.egg/clockwork/tasks/make_empty_db.py", line 5, in run
  File "/usr/local/lib/python3.8/dist-packages/clockwork-0.11.1-py3.8.egg/clockwork/db_maker.py", line 9, in __init__
Exception: Error connecting to database
```

My `db.ini` file contains the following:
```
[db_login]
user = root
password = somepassword
host = localhost
db = clockwork
```

Both `container.img` and `db.ini` file are in the same directory.   

Furthermore, if my `ini` does not have the `[db_login]` section, this error is not caught when trying to read the config file in `db_connection.py` file:
```
           @classmethod
    4     def _parse_config_file(cls, ini_file):
    3         config = configparser.ConfigParser()
    2         try:
    1             config.read(ini_file)
  46          except:
    1             raise Exception("Error! [db_login] section not in file " + ini_file)
    2
    3         expected_keys = {"user", "password", "host", "db"}
    4         got_keys = set(config["db_login"].keys())
```

**Comment by martinghunt** [comment]
I can only reproduce the `KeyError: 'db_login'` error if either I use the wrong name for the config file (which, I know, is not a good error message!), or if there's no `[db_login]` section. Could you please double-check there's no typo in the filename?

**Comment by PPrasai** [comment]
I actually wrote a small python script to make sure that the try catch block between lines 44 and 47 actually catches errors.
Following is the script I used to test this:
```
import configparser

config = configparser.ConfigParser()
try:
    config.read('conf.ini')
except:
    raise Exception('Message here')

print(dict(config['db_config']))
```

Following were the test scenarios:
```No file named 'conf.ini' present``` raised ```KeyError: 'db_config'``` on the last line
```File exists, but 'db_config' section doesn't``` raised same error as above
```File exists, section exists``` prints the ```dict``` successfully.

I solved my initial problem by simply creating a working directory and running all ```singularity exec``` commands like so:    

> **singularity exec -H /absolute/path/to/working/dir** clockwork.img clockwork make_empty_db db.ini
