### ISSUE TITLE
How to access the output?

### ISSUE THREAD

**Issue by Mor-Rubinsteinn** [iqbal-lab-org/clockwork#92]
clockwork was installed on my server with a database. It runs OK, but I would like to know what is the best way to access the pipeline outputs. In particular, I would like to be able to export:
1. the variant table, 
2. the number or % of reads annotated to each reference genome (or any other form of report with the details of the contamination step.
3. Is it possible to get some FASTQC-like output? in particular the 'Per base sequence quality'
4. Mapping statistics - median/average depth and coverage breadth.

Thanks so much

**Comment by martinghunt** [comment]
Apologies, none of this was documented. I've made a new wiki page:
https://github.com/iqbal-lab-org/clockwork/wiki/Pipeline-outputs

The wiki should answer your questions. Briefly:
1. There's a VCF file made for each isolate, you need to use that. Variants are not stored in the database.
2. You can get overall numbers from the database (sql is on the wiki), or complete details in the files on disk.
3. Yes. fastqc and samtools stats are on disk. Most of their numbers are also in the database.
4. Mean depth is possible, but sorry breadth is not recorded.

Hope that helps!

**Comment by Mor-Rubinsteinn** [comment]
Thanks for answering so quickly. I'll have a look
