### ISSUE TITLE
Error when running qc.nf

### ISSUE THREAD

**Issue by dpenas-u** [iqbal-lab-org/clockwork#94]
To execute quality control on fastq files, the command supplied in the tutorial is: 

nextflow run nextflow/qc.nf \
  -with-singularity clockwork_container.img \
  --ref_fasta Ref.QC_and_map/ref.fa \
  --reads_in1 reads_1.fastq --reads_in2 reads_2.fastq \
  --output_dir qc_out

(I am able to prepare the reference genome). However, I get the following error:

N E X T F L O W  ~  version 22.04.0
Launching `../nextflow/qc.nf` [elegant_carlsson] DSL2 - revision: 4bda30ed1d
No such variable: jobs_tsv_channel

 -- Check script 'nextflow/qc.nf' at line: 154 or see '.nextflow.log' file for more details

I don't know if I have to specify something else when running nextflow. On the other hand, if I silence that line, I get the following error:

N E X T F L O W  ~  version 22.04.0
Launching `../nextflow/qc.nf` [agitated_mestorf] DSL2 - revision: e5636d66a5
Missing workflow definition - DSL2 requires at least a workflow block in the main script

I seems that a workflow has not been defined in the qc.nf file. 

If anyone knows how to solve the problem, please, let me know. Thank you

**Comment by martinghunt** [comment]
I think this is caused by a nextflow version >= 22.03 defaulting to their new language version.

Could you try this before running the pipeline?

```
export NXF_DEFAULT_DSL=1
```

If that works, I'll update the scripts...

**Comment by dpenas-u** [comment]
You were right. Changing DSL1 it perfectly worked.

Thank you very much for your help !!!!!

**Comment by martinghunt** [comment]
Great! Thanks for confirming. I'll leave this issue open for now to remind me to fix the nextflow scripts, so that workaround won't be needed in future

**Comment by martinghunt** [comment]
All the nextflow scripts now specify DSL1 (commit d038ca8cb133080ed47b40bccea8a73f01cade2d)
