### ISSUE TITLE
I don't know what's wrong

### ISSUE THREAD

**Issue by s1df4i** [iqbal-lab-org/clockwork#98]
some cases can get final.vcf ,but most cases are encountering the error below when I when I try to run the following command ,and I don't known how to solve it:

singularity exec clockwork.img clockwork variant_call_one_sample --sample_name TB2447 Ref.H37Rv Var_call_TB2447 TB2447.decontam_1.fq.gz TB2447.decontam_2.fq.gz

<img width="1438" alt="截屏2022-08-10 上午10 03 01" src="https://user-images.githubusercontent.com/108961947/183795459-33d6ac58-d81b-4195-83b5-6aa4c341736f.png">

Would you have any idea what could be going on and what I can do to solve this? Is the problem on your end or mine? Any insight will be most appreciated thank you!

**Comment by martinghunt** [comment]
Thanks for reporting, that was a fun one to debug!

I'm fixing the problem, but a workaround for now is to use a sample name that is not 6 characters long.

**Comment by martinghunt** [comment]
New release 0.11.2 has the fix
